roles:
  - geerlingguy.git
  - weareinteractive.sudo
  - manala.make
  - geerlingguy.php
  - geerlingguy.php-versions
  - geerlingguy.postgresql
  - geerlingguy.php-pgsql
  - geerlingguy.mysql
  - geerlingguy.php-mysql
  - manala.cron
  - geerlingguy.nginx
  - geerlingguy.composer
  - geerlingguy.certbot
  - geerlingguy.nodejs
  - ricsanfre.minio
  - oefenweb.yarn
  - kh-eek.ghostscript
