---
prod:
  hosts:
    {{server_ip}}
  vars:
    dotenv_file_template: "templates/.env.{{site_name}}.prod"
    nginx_vhosts:
      - listen: "80"
        server_name: "{{dns}}.net www.{{dns}}.net"
        filename: "{{site_name}}.conf"
        root: "/var/www/{{site_name}}/current/public"
        state: "present"
        extra_parameters: |
          location / {
              try_files $uri /index.php$is_args$args;
          }
          location ~ ^/index\.php(/|$) {
              fastcgi_split_path_info ^(.+\.php)(/.*)$;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_param APP_ENV prod;
              fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
              fastcgi_param DOCUMENT_ROOT $realpath_root;
              include fastcgi_params;
              internal;
          }
          location ~ \.php$ {
              return 404;
          }
        access_log: "/var/log/nginx/pro_access.log"
        error_log: "/var/log/nginx/pro_error.log"
