---
- name: Override Imagick Policy
  template:
    src: templates/imagick-policy.xml
    dest: /etc/ImageMagick-6/policy.xml
    owner: root
    group: root
    mode: 0644

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: "restarted"
