---
- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Fedora"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Define ghopstscript_install_from_source_dependencies.
  set_fact:
    ghopstscript_install_from_source_dependencies: "{{ __ghopstscript_install_from_source_dependencies | list }}"
  when: ghopstscript_install_from_source_dependencies is not defined

- name: Ensure ghostscript's dependencies are installed.
  package:
    name: "{{ ghopstscript_install_from_source_dependencies }}"
    state: present

- name: Get installed version.
  command: >
    ghostscript --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: ghostscript_installed_version

- name: Force ghostscript install if the version numbers do not match.
  set_fact:
    ghostscript_reinstall_from_source: true
  when:
    - (ghostscript_installed_version.rc == 0) and (ghostscript_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") is version(ghostscript_version, operator="!="))

- name: Download ghostscript.
  get_url:
    url: "https://www.kernel.org/pub/software/scm/ghostscript/ghostscript-{{ ghostscript_version }}.tar.gz"
    dest: "{{ workspace }}/ghostscript-{{ ghostscript_version }}.tar.gz"
  when: (ghostscript_installed_version.rc != 0) or (ghostscript_reinstall_from_source | bool)

- name: Expand ghostscript archive.
  unarchive:
    src: "{{ workspace }}/ghostscript-{{ ghostscript_version }}.tar.gz"
    dest: "{{ workspace }}"
    creates: "{{ workspace }}/ghostscript-{{ ghostscript_version }}/README"
    copy: false
  when: (ghostscript_installed_version.rc != 0) or (ghostscript_reinstall_from_source | bool)

- name: Build ghostscript.
  command: >
    make prefix={{ ghostscript_install_path }} {{ item }}
    chdir={{ workspace }}/ghostscript-{{ ghostscript_version }}
  with_items:
    - all
    - install
  when: (ghostscript_installed_version.rc != 0) or (ghostscript_reinstall_from_source | bool)
  become: true
