ansible_ssh_user: root
certbot_auto_renew: false
php_enable_php_fpm: true
php_enable_webserver: false
php_date_timezone: Europe/Paris
php_memory_limit: "1024M"
php_packages_state: latest
nginx_remove_default_vhost: true
php_packages_extra:
  - php-zip
  - php-intl
  - php-imagick
  - php7.4-zip
  - php7.4-intl
  - php7.4-imagick
