---
- name: Downlaod GhostScript archive
  get_url:
    url: "{{ gs_download_url }}"
    dest: "{{ gs_archive_dir }}"
    checksum: "{{ gs_archive_checksum }}"
    timeout: 120

- name: Unarchive GhostScript
  unarchive:
    src: "{{ gs_archive_dir }}"
    dest: "{{ gs_unarchive_dir }}"
    remote_src: True
    creates: "{{ gs_unarchive_dir }}/configure"

- name: Running "./configure" for GhostScript
  command: "./configure"
  args:
    chdir: "{{ gs_unarchive_dir }}/{{ gs_archive }}"
    creates: "{{ gs_unarchive_dir }}/{{ gs_archive }}/Makefile"

- name: Running "make" for GhostScript
  command: "make"
  args:
    chdir: "{{ gs_unarchive_dir }}/{{ gs_archive }}"
    removes: "{{ gs_unarchive_dir }}/{{ gs_archive }}/Makefile"

- name: Running "make install" for GhostScript
  command: "make install"
  args:
    chdir: "{{ gs_unarchive_dir }}/{{ gs_archive }}"
    removes: "{{ gs_unarchive_dir }}/{{ gs_archive }}/Makefile"

- name: Download GhostScript fonts
  get_url:
    url: "{{ gs_fonts_download_url }}"
    dest: "/tmp/ghostscript-fonts-std-8.11.tar.gz"
    timeout: 300
  when: gs_fonts_install

- name: Unarchive GhostScript fonts
  unarchive:
    src: "/tmp/ghostscript-fonts-std-8.11.tar.gz"
    dest: "/usr/local/share/ghostscript/"
    remote_src: True
  when: gs_fonts_install
