---
- name: Generate SSH Keypair.
  openssh_keypair:
    path: "/var/www/.ssh/{{ssh_key_filename}}"
    type: ed25519
    state: present
    force: no

- name: Change ssh private key owner to www-data
  ansible.builtin.file:
    path: /var/www/.ssh/{{ssh_key_filename}}
    owner: www-data
    group: www-data

- name: Change ssh public key owner to www-data
  ansible.builtin.file:
    path: /var/www/.ssh/{{ssh_key_filename}}.pub
    owner: www-data
    group: www-data

- name: Read content of www-data ssh public key
  command: cat {{ssh_key_filename}}.pub chdir=/var/www/.ssh
  register: ssh_public_key_content

- name: Display content of www-data ssh public key
  debug:
    msg: "{{ssh_public_key_content.stdout}}"