nginx_vhosts:
  - listen: "80"
    # server_name: "preprod.pro.reconnect.fr www.preprod.pro.reconnect.fr"
    server_name: "new.preprod.pro.reconnect.fr"
    filename: "rp.conf"
    root: "/var/www/rp/current/public"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      location / {
          try_files $uri /index.php$is_args$args;
      }
      location ~ ^/index\.php(/|$) {
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param APP_ENV prod;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
          include fastcgi_params;
          internal;
      }
      location ~ \.php$ {
          return 404;
      }
    access_log: "/var/log/nginx/rp_access.log"
    error_log: "/var/log/nginx/rp_error.log"
