---
- name: Creates shared directory if not exist
  file:
    path: "{{ dotenv_file_location }}"
    state: directory

- name: Create a templated .env.
  template:
    src: "{{ dotenv_file_template }}"
    dest: "{{ dotenv_file_location }}/.env"
    owner: www-data
    group: www-data
  when: site_name is defined and dotenv_file_template is defined
