---
- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Fedora"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Define ghopstscript_install_from_source_dependencies.
  set_fact:
    ghopstscript_install_from_source_dependencies: "{{ __ghopstscript_install_from_source_dependencies | list }}"
  when: ghopstscript_install_from_source_dependencies is not defined

- name: Ensure python_certbot_nginx's dependencies are installed.
  package:
    name: "{{ ghopstscript_install_from_source_dependencies }}"
    state: present

- name: Get installed version.
  command: >
    python_certbot_nginx --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: python_certbot_nginx_installed_version

- name: Force python_certbot_nginx install if the version numbers do not match.
  set_fact:
    python_certbot_nginx_reinstall_from_source: true
  when:
    - (python_certbot_nginx_installed_version.rc == 0) and (python_certbot_nginx_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") is version(python_certbot_nginx_version, operator="!="))

- name: Download python_certbot_nginx.
  get_url:
    url: "https://www.kernel.org/pub/software/scm/python_certbot_nginx/python_certbot_nginx-{{ python_certbot_nginx_version }}.tar.gz"
    dest: "{{ workspace }}/python_certbot_nginx-{{ python_certbot_nginx_version }}.tar.gz"
  when: (python_certbot_nginx_installed_version.rc != 0) or (python_certbot_nginx_reinstall_from_source | bool)

- name: Expand python_certbot_nginx archive.
  unarchive:
    src: "{{ workspace }}/python_certbot_nginx-{{ python_certbot_nginx_version }}.tar.gz"
    dest: "{{ workspace }}"
    creates: "{{ workspace }}/python_certbot_nginx-{{ python_certbot_nginx_version }}/README"
    copy: false
  when: (python_certbot_nginx_installed_version.rc != 0) or (python_certbot_nginx_reinstall_from_source | bool)

- name: Build python_certbot_nginx.
  command: >
    make prefix={{ python_certbot_nginx_install_path }} {{ item }}
    chdir={{ workspace }}/python_certbot_nginx-{{ python_certbot_nginx_version }}
  with_items:
    - all
    - install
  when: (python_certbot_nginx_installed_version.rc != 0) or (python_certbot_nginx_reinstall_from_source | bool)
  become: true
